<a href="https://colab.research.google.com/github/Lucas-Abrahao/Alura-Python-para-DS/blob/main/Introdu%C3%A7%C3%A3o_a_Linguagem_e_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Verificando a Versão do Python

In [1]:
!python -V

Python 3.7.13


##Trabalhando com Arrays NumPy

In [2]:
import numpy as np

##Carregando Arquivos .txt

In [3]:
km = np.loadtxt('/content/carros-km.txt')

###Atribuindo Tipos as Variaveis do Arquivo

In [4]:
anos = np.loadtxt('/content/carros-anos.txt',dtype = int)

##Obtendo a Kilometragem Média por Ano

In [5]:
km_media = km / (2021 - anos)

In [6]:
km_media

array([2.46722222e+03, 1.90400000e+02, 1.19751613e+03, 0.00000000e+00,
       1.71713333e+03, 1.19200000e+03, 0.00000000e+00, 6.46658333e+03,
       9.01790909e+03, 3.79780000e+03, 6.76789474e+02, 5.75142857e+02,
       4.48865000e+03, 0.00000000e+00, 3.45475000e+03, 2.31214000e+04,
       5.16100000e+03, 0.00000000e+00, 7.41720000e+03, 3.79325000e+03,
       5.32594737e+03, 0.00000000e+00, 3.63255556e+03, 3.43196667e+03,
       0.00000000e+00, 0.00000000e+00, 1.15900000e+03, 0.00000000e+00,
       3.09726316e+03, 3.14603333e+03, 1.25679167e+03, 2.05123077e+03,
       5.90666667e+03, 1.12693333e+03, 1.29548571e+04, 1.69134615e+03,
       0.00000000e+00, 0.00000000e+00, 4.60500000e+02, 0.00000000e+00,
       1.16768750e+04, 2.26455556e+03, 0.00000000e+00, 4.54221053e+03,
       0.00000000e+00, 5.13421053e+02, 4.11441176e+03, 1.19750000e+02,
       0.00000000e+00, 4.46383333e+03, 7.12950000e+03, 3.36640000e+03,
       3.22457143e+03, 6.26313333e+03, 3.21318182e+03, 3.00025926e+03,
      

##Operações Matemáticas com Python

###Adição

In [7]:
2 + 2

4

###Subtração

In [8]:
4 - 2

2

###Multiplicação

In [9]:
2 * 2

4

###Divisão (/) (//)

In [10]:
10/3

3.3333333333333335

In [11]:
10//3

3

###Exponenciação

In [12]:
2**3

8

###Resto da Divisão %

In [13]:
10%3

1

###Expressões Matemáticas

In [14]:
5*2+3*2

16

In [15]:
(5*2)+(3*2)

16

In [16]:
5*(2+3)*2

50

###A Variável _

In [17]:
_

50

In [18]:
_ /2

25.0

In [19]:
_ - 15

10.0

##Conversão de Tipos

In [20]:
a = 30
b = 20
pi = 3.141592
c = 'Lucas'
d = ' Abrahão'

In [21]:
a + b

50

In [22]:
type(a)

int

In [23]:
str(a)

'30'

In [24]:
type(str(a))

str

In [25]:
c + d

'Lucas Abrahão'

##Formatação de Strings

###str.format()

In [26]:
print('Olá {}!'.format('Lucas'))

Olá Lucas!


In [27]:
print('Olá {}, Este é seu acesso de número {}'.format('Lucas',5489))

Olá Lucas, Este é seu acesso de número 5489


In [28]:
print('Olá {nome}, Este é seu acesso de número {acessos}'.format(nome = 'Lucas', acessos = 5489))

Olá Lucas, Este é seu acesso de número 5489


###f-strings

In [29]:
nome = 'Lucas'
acessos = 5489

In [30]:
print(f'Olá {nome}, Este é seu acesso de número {acessos}')

Olá Lucas, Este é seu acesso de número 5489


##Listas

In [31]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [32]:
type(Acessorios)

list

In [33]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]

In [34]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [35]:
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [36]:
carros = [Carro_1,Carro_2]
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

###Operações com Listas

####X in A

Retorna True SE um Elemento de A for Igual a X

In [37]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [38]:
'Rodas de liga' in Acessorios

True

In [39]:
'4 x 4' in Acessorios

False

In [40]:
'Rodas de liga' not in Acessorios

False

In [41]:
'4 x 4' not in Acessorios

True

####A + B

Concatena Duas Listas

In [42]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [43]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [44]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [45]:
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [46]:
C = A + B

In [47]:
C

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

####len(A)

Tamanho da Lista

In [48]:
len(C)

8

###Seleções em Listas

In [49]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [50]:
Acessorios[0]

'Rodas de liga'

In [52]:
Acessorios[3]

'Bancos de couro'

In [53]:
Acessorios[-1]

'Sensor de chuva'

In [54]:
carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [55]:
carros[0][0]

'Jetta Variant'

In [56]:
carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [57]:
carros[0][-2][1]

'Travas elétricas'

####Slices A[I:J]

I é o Primeiro Valor da Lista // 
J é o Final, Não Entra na Lista, Somente o Valor Anterior

In [58]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [59]:
Acessorios[2:5]
#2 = Piloto Automatico
#5 = Sensor de Estacionamento

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [60]:
Acessorios[2:]
# Não colocar nada significa ir até o final da lista

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [61]:
Acessorios[:5]
#O mesmo é valido no começo

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

###Métodos em Listas

In [62]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [63]:
Acessorios.sort()
#Ordena alfabéticamente ou numéricamente
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [64]:
Acessorios.append('4x4')
#Adiciona um item ao final da Lista
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4x4']

In [65]:
Acessorios.pop()
#remove um item da lista, se não houver numero no indice remove o ultimo item

'4x4'

In [66]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [67]:
Acessorios2 = Acessorios.copy()
#Copia a lista
Acessorios2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [68]:
Acessorios2.append('4 x 4')

In [69]:
Acessorios.append('Travas elétricas')

In [70]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Travas elétricas']

In [71]:
Acessorios2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [73]:
Acessorios.copy()
#É equivalente a
Acessorios[:]

Acessorios2 = Acessorios.copy()
#          OU
Acessorios2 = Acessorios[:]

##Estruturas de Repetição

In [74]:
quadrado = []

for i in range(10):
  quadrado.append( i ** 2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [75]:
[i ** 2 for i in range (10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

###Loops Aninhados

In [76]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [77]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [78]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [79]:
acessorios = []

for lista in dados:
  for item in lista:
    acessorios.append(item)

acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

####set()

In [80]:
list(set(acessorios))

['Travas elétricas',
 'Painel digital',
 'Teto panorâmico',
 'Rodas de liga',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Freios ABS',
 'Sensor de estacionamento',
 '4 X 4',
 'Ar condicionado',
 'Vidros elétricos',
 'Central multimídia',
 'Piloto automático',
 'Câmbio automático',
 'Bancos de couro',
 'Câmera de estacionamento']

OU

In [81]:
list(set([item for lista in dados for item in lista]))

['Travas elétricas',
 'Painel digital',
 'Teto panorâmico',
 'Rodas de liga',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Freios ABS',
 'Sensor de estacionamento',
 '4 X 4',
 'Ar condicionado',
 'Vidros elétricos',
 'Central multimídia',
 'Piloto automático',
 'Câmbio automático',
 'Bancos de couro',
 'Câmera de estacionamento']

##IF

In [82]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

###Mostre Apenas os Veículos Zero KM

In [83]:
zero_km = []

for lista in dados:
  if(lista[2] == True):
    zero_km.append(lista)

zero_km

[['DS5', 2019, True], ['A5', 2019, True]]

In [84]:
zero_km_f = []

for lista in dados:
  if(lista[2] == False):
    zero_km_f.append(lista)

zero_km_f

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

OU

In [85]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

##Array e NumPy

###Importando

In [86]:
import numpy

###Usando arange

In [87]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###Importando Todo o Pacote e Atribuindo um Nome

In [88]:
import numpy as np

In [89]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###Importando Parte do Pacote

In [90]:
from numpy import arange

In [91]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Criando Arrays NumPy

###A Partir de Listas

In [92]:
km = np.array([1000, 2300, 4937])

In [93]:
km

array([1000, 2300, 4937])

In [94]:
type(km)

numpy.ndarray

In [95]:
km.dtype

dtype('int64')

###A Partir de Dados Externos

In [96]:
km = np.loadtxt(fname = '/content/carros-km.txt', dtype = int)

In [97]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [98]:
km.dtype

dtype('int64')

In [99]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [100]:
acessorios = np.array(dados)

In [101]:
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [102]:
km.shape

(258,)

In [103]:
acessorios.shape

(3, 8)

###Comparando Desempenho com Listas

In [104]:
np_array = np.arange(1000000)

In [105]:
py_list = list(range(1000000))

In [106]:
%time for _ in range (100): np_array *= 2

CPU times: user 68.8 ms, sys: 0 ns, total: 68.8 ms
Wall time: 70.2 ms


In [107]:
%time for _ in range (100) : py_list = [ x * 2 for x in py_list]

CPU times: user 10.1 s, sys: 2.52 s, total: 12.7 s
Wall time: 12.8 s


##Operações Aritméticas com Array Numpy

###Operações Entre Arrays e Constantes

In [108]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [109]:
idade = 2021 - anos

TypeError: ignored

In [110]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [111]:
idade = 2021 - anos

In [112]:
idade

array([18, 30, 31,  2, 15])

##Operações Entre Arrays

In [113]:
km_media = 0
km_media = km / idade

In [114]:
km_media

array([2467.22222222,  190.4       , 1197.51612903,    0.        ,
       1717.13333333])

##Operações com Arrays de Duas Dimensões

In [115]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [116]:
dados.shape

(2, 5)

In [117]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [118]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [119]:
km_media = dados[0] / ( 2021 - dados[1])
km_media

array([2467.22222222,  190.4       , 1197.51612903,    0.        ,
       1717.13333333])

##Seleções com Arrays e NumPy

In [120]:
dados[1][2]

1990.0

In [121]:
dados[1,2]

1990.0

##Fatiamento

In [122]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
contador[1:4]

array([1, 2, 3])

In [124]:
contador[1:8:2]

array([1, 3, 5, 7])

In [125]:
contador[::2]

array([0, 2, 4, 6, 8])

In [126]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [127]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [128]:
dados[:, 1 :4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [129]:
dados[:, 1 :3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

##Indexação com Array Booleano

In [130]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [132]:
contador [contador > 5]

array([6, 7, 8, 9])

In [133]:
contador [[False, False, False, False, False, False,  True,  True,  True,
        True]]

array([6, 7, 8, 9])

In [134]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [135]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [136]:
dados[:,dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

##Atributos com Arrays NumPy

In [137]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [138]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

###shape

In [139]:
dados.shape

(2, 5)

###ndim

In [140]:
dados.ndim

2

###Size

In [141]:
dados.size

10

###dtype

In [142]:
dados.dtype

dtype('float64')

###.T (Transposta)

In [143]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [144]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

##Métodos com Array NumPy

###tolist()

In [145]:
dados.tolist()
#Transforma em Lista

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

###reshape()

In [146]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
contador.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [148]:
contador.reshape((5,2), order = 'C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [149]:
contador.reshape((5,2), order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [150]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [151]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [152]:
np.array(info_carros)

array([44410,  5712, 37123,     0, 25757,  2003,  1991,  1990,  2019,
        2006])

In [153]:
np.array(info_carros).reshape(2,5)

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [154]:
np.array(info_carros).reshape((5,2), order = 'F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

###resize()

In [155]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [156]:
dados_new.resize((3,5), refcheck = False)

In [157]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [158]:
dados_new[2] = dados_new[0] / (2021 - dados_new[1])

In [159]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2467.22222222,   190.4       ,  1197.51612903,     0.        ,
         1717.13333333]])

##Estatísticas com Array NumPy

In [160]:
anos = np.loadtxt(fname = "/content/carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "/content/carros-km.txt")
valor = np.loadtxt(fname = "/content/carros-valor.txt")

In [161]:
anos.shape

(258,)

In [162]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [163]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [164]:
np.mean(dataset[:,1])

44499.41472868217

In [165]:
np.mean(dataset[:,2])

98960.51310077519

In [166]:
np.std(dataset[:,2])
#desvio padrão

29754.101150388564

In [167]:
dataset[:,1].sum()

11480849.0

In [168]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])